server:
  port: 8012
spring:
  application:
    name: yl-demo2
  cloud:
    nacos:
      discovery:
        server-addr: 139.224.202.194:8848
        username: nacos
        password: nacos
        namespace: 136bb874-5f45-4086-bc11-0ae4d1f926be
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.224.202.194:3306/yl_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456