server:
  port: 8015
spring:
  application:
    name: yl-gateway
  cloud:
    #gateway配置
    gateway:
#      discovery:
#        locator:
#          enabled: true
      #路由规则
      routes:
        - id: demo1_route  #路由的唯一标识
          uri: lb://yl-demo1  #需要转发的地址
          #断言规则 用于路由规则匹配
          predicates:
            - Path=/demo-service/**
          filters:
            - StripPrefix=1
    nacos:
      discovery:
        server-addr: 139.224.202.194:8848
        username: nacos
        password: nacos